### ISSUE TITLE
Required fields in Helm templates causes templating of helm charts to not work

### ISSUE THREAD

**Issue by onedr0p** [allenporter/flux-local#467]
Some Helm charts have `required` options in the templates which can cause the templating to fail if using Flux `valuesFrom` in Helm Releases. See [this link](https://github.com/actions/actions-runner-controller/blob/1f9b7541e6545a9d5ffa052481a84aad7ba4aa4d/charts/gha-runner-scale-set/templates/githubsecret.yaml#L34) for an example. I am able to install these because I use Flux's `valuesFrom` like in [this](https://github.com/onedr0p/home-ops/blob/579149dd36996be1f050bfbc7e825a7a4b6daa20/kubernetes/main/apps/actions-runner-system/actions-runner-controller/runners/helmrelease.yaml#L26-L38) `HelmRelease`, however `helm template` fails:

```
Error: execution error at (gha-runner-scale-set/templates/githubsecret.yaml:34:8): A valid .Values.githubConfigSecret is required for setting auth with GitHub server, provide .Values.githubConfigSecret.github_token or .Values.githubConfigSecret.github_app_id.
```

I am not sure if there is a way around this, because Helm doesn't provide an option to ignore these errors when using `helm template`. 😢 I guess we can leave this issue open for awareness if anything?

**Comment by allenporter** [comment]
Emulating `valuesFrom` seems reasonable. Perhaps when there is a `flux build hr` it'll take care of this....

**Comment by onedr0p** [comment]
Unfortunately it's blocking my use for https://github.com/allenporter/flux-local/issues/434 since I get the same error as it tries to extract all the images.

**Comment by allenporter** [comment]
I can see in your cluster that the referenced secret `actions-runner-controller-auth-secret` doesn't exist, but is created by `ExternalSecret` so it can't really be discovered.

Perhaps just always dumping a synthetic value into `targetPath` would be the way to go, without doing any verification that it can be found in the cluster.

**Comment by allenporter** [comment]
Perhaps it would need an option (later at least) to be explicit given the contents of the values may matter for the helm validation if they are more complex.
