### ISSUE TITLE
Github actions diff - Argument list too long

### ISSUE THREAD

**Issue by tropnikovvl** [allenporter/flux-local#623]
Hello!

If you make a diff of a large number of changes, you may encounter the error that the `arguments list too long`.

This is most likely due to the fact that you are putting the output into a variable.
https://github.com/allenporter/flux-local/blob/main/action/diff/action.yml#L116

Is it possible to do optional output to a file? Which I could then read and pass on to another action

<img width="1384" alt="Screenshot 2024-04-19 at 16 25 40" src="https://github.com/allenporter/flux-local/assets/76093012/a9925401-fdc6-4d39-baf5-1253035a3208">

**Comment by allenporter** [comment]
Thank you for the report. Tracking this in #207 so deduping
