### ISSUE TITLE
[v5.3.0] GitHub Actions fail to install requirements

### ISSUE THREAD

**Issue by gabe565** [allenporter/flux-local#673]
Hello! I just upgraded from v5.2.0 to v5.3.0, and the diff action has started failing during dependency installation with an error. [Here](https://github.com/gabe565/home-ops/actions/runs/9068779392/job/24916840509#step:4:59) is an action run that includes the error, or see below.
```
Obtaining file:///home/runner/work/home-ops/home-ops (from -r ./tmp.ej7Igm7FJe-flux-local-diff-action/requirements.txt (line 1))
ERROR: file:///home/runner/work/home-ops/home-ops (from -r ./tmp.ej7Igm7FJe-flux-local-diff-action/requirements.txt (line 1)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

I suspect this is due to [`-e .`](https://github.com/allenporter/flux-local/blob/main/requirements.txt#L1) which was recently added to `requirements.txt`. It seems like that line is causing pip to try to install my gitops repo instead of flux-local, but I don't have enough background info to know the reasoning. Should the GitHub Action set the working directory to `${{ github.action_path }}` for the `pip install` step?

**Comment by allenporter** [comment]
Yeah good catch, we can rely on the `-e` that is already present here https://github.com/allenporter/flux-local/blob/941237cb795041528901be058d0e0830416b9c28/action/diff/action.yml#L78

**Comment by gabe565** [comment]
@allenporter Oh that makes total sense. Thanks for the quick response!

**Comment by allenporter** [comment]
Now testing 5.3.1 which includes a potential fix

**Comment by allenporter** [comment]
Seems to be working ok for me: https://github.com/allenporter/k8s-gitops/actions/runs/9073774564 

Let me know if you run into any problems.
