### ISSUE TITLE
HelmRelease diff not showing changes based on values files

### ISSUE THREAD

**Issue by Lingkar** [allenporter/flux-local#817]
When making changes in a helm release values file coming from a ConfigMap with a static name, without making any direct changes to the helmRelease resource.
The helm release diff command does not show any helm release differences.

This seems to be caused by the logic explained in a comment found in the class DiffHelmReleaseAction in ./tool/diff.py.
```      
# Find HelmRelease objects with diffs and prune all other HelmReleases from
# the helm visitors. We assume that the only way for a HelmRelease output
# to have a diff is if the HelmRelease in the kustomization has a diff.
# This avoid building unnecessary resources and churn from things like
# random secret generation.
```

**Comment by allenporter** [comment]
Thanks for the report. Can you confirm that the `build` command on the two different versions of the repo shows the resulting differences you expect?

**Comment by allenporter** [comment]
My assumption is that we need to build a small graph of resources that a `HelmRelease` may reference and also look for diffs on those to preserve this optimization. Namely things like `HelmRelease` or `ConfigMap`, etc.
